# -*- coding: utf-8 -*-
"""week 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvbXT8fBSUQO4WRW6HXpDpePsLD39Obz

**Load data from data.csv**
"""

import pandas as pd
import matplotlib.pyplot as plt

# pd.options.display.max_rows = 999

df = pd.read_csv('data.csv')

#reading the first 10 rows
print(df.head(10))

"""**Mean of calories**"""

df['Calories'].mean()

"""**Mode of Pulse**"""

df['Pulse'].mode()[0]

"""**Median for calories**"""

df['Calories'].median()

"""**Line chart**"""



"""**Bar chart**"""



"""**Histograph**"""

df['Duration'].plot(kind='hist')

"""**Scatter plot**"""

#Removing empty cells
df.dropna(inplace=True)
#Plotting scatter plot
df.plot(x='Duration',y='Calories',kind='scatter')
plt.show()